### ISSUE TITLE
Add only version specific files in version directories

### ISSUE THREAD

**Issue by mordechaim** [metlos/multi-release-jar-maven-plugin#4]
It looks like the plugin compiler doesn't fall back to look for `src/main/java` for files that are non-version specific. This would require to add _all_ files to both directories and track all trivial changes among both locations.

It would be great if we can just place the version specific files into the version specific directory.

**Comment by mordechaim** [comment]
Any plans on this?

**Comment by metlos** [comment]
Could you describe your problem in more detail? Because the integration test (https://github.com/metlos/multi-release-jar-maven-plugin/tree/master/src/it/basic) does exactly what you describe as not possible...

**Comment by mordechaim** [comment]
You are right, I guess I didn't use it properly.
